### ISSUE TITLE
How to add multiple IP addresses under the "notify:" in configuration.yaml?

### ISSUE THREAD

**Issue by satyajitmishra93** [LAB02-Research/HASS.Agent-Notifier#19]
I was able to add one of my windows desktop running HASS Agent & use its notification feature. But I want to added another one of my windows desktop. Can someone please tell me how I can add mutltiple desktops/IPs under the "notify:" in configuration.yaml?

**Comment by LAB02-Admin** [comment]
You can make multiple notify entities, one per device. If you want to send a notification to all of them at once, use notify groups:

https://www.home-assistant.io/integrations/group/#notify-groups

**Comment by satyajitmishra93** [comment]
I tried to make mutiple notify entities, but it didn't work. Below is the code that I tried;
notify: 
  name: "Device One"
  platform: hass_agent_notifier
  resource: http://192.168.0.101:5115/notify
  name: "Device Two"
  platform: hass_agent_notifier
  resource: http://192.168.0.102:5115/notify

Can you please tell me how I can create mutiple notify entities so that I can use them separetely?

**Comment by LAB02-Admin** [comment]
Try this:

```yaml
notify: 
  name: device_one
  platform: hass_agent_notifier
  resource: http://192.168.0.101:5115/notify

notify:
  name: device_two
  platform: hass_agent_notifier
  resource: http://192.168.0.102:5115/notify
```

And then as the group:

```yaml
notify:
  name: hassagent_group
  platform: group
  services:
    - service: device_one
    - service: device_two
```
