### ISSUE TITLE
Notification issue as well

### ISSUE THREAD

**Issue by noideaman** [LAB02-Research/HASS.Agent-Notifier#6]
like #2 i am having notification issues on windows 10. firewall port 5115 is open on tcp
![image](https://user-images.githubusercontent.com/39884745/152624742-384446c3-6bd0-4275-accf-a3549750912f.png)
added the notification entity in config.yaml and it shows in automations
```yaml
notify: 
  name: "reepc"
  platform: hass_agent_notifier
  resource: http://192.168.6.32:5115/notify
  ```
  
![image](https://user-images.githubusercontent.com/39884745/152624813-2c16f2e7-0886-44fe-bcef-353a7868aa21.png)
running curl from with in HA shows 

```bash
curl -i http://192.168.6.32:5115
HTTP/1.1 200 OK
Content-Length: 17
Server: Grapevine/5.0.0.0 (Microsoft Windows 10.0.19043 ) Microsoft-HTTPAPI/2.0
Date: Sat, 05 Feb 2022 02:09:39 GMT

HASS.Agent Active#
```
and it is installed in ha via hacs
![image](https://user-images.githubusercontent.com/39884745/152624909-825570f0-309b-419c-bbae-32120be28988.png)
